<a href="https://colab.research.google.com/github/sahanasubbiah24/churn-prediction/blob/main/notebooks/02_numpy_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
monthly_charges = np.array([
    29.99,
    54.50,
    72.25,
    89.99,
    45.00
])

print(monthly_charges)
print(type(monthly_charges))

[29.99 54.5  72.25 89.99 45.  ]
<class 'numpy.ndarray'>


In [3]:
print("Shape:", monthly_charges.shape)
print("Dimensions:", monthly_charges.ndim)
print("Number of values:", monthly_charges.size)
print("Data type:", monthly_charges.dtype)

Shape: (5,)
Dimensions: 1
Number of values: 5
Data type: float64


In [4]:
numbers_zero_to_nine = np.arange(10)
print(numbers_zero_to_nine)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
numbers_one_to_twenty = np.arange(1, 21)
print(numbers_one_to_twenty)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
zeros = np.zeros(5)
ones = np.ones(5)

print(zeros)
print(ones)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [7]:
annual_charges = monthly_charges * 12

print(annual_charges)

[ 359.88  654.    867.   1079.88  540.  ]


In [8]:
discounted_charges = monthly_charges * 0.90
increased_charges = monthly_charges * 1.05

print("10% discount:", discounted_charges)
print("5% increase:", increased_charges)

10% discount: [26.991 49.05  65.025 80.991 40.5  ]
5% increase: [31.4895 57.225  75.8625 94.4895 47.25  ]


In [9]:
rounded_annual_charges = np.round(
    annual_charges,
    decimals=2
)

print(rounded_annual_charges)

[ 359.88  654.    867.   1079.88  540.  ]


In [11]:
monthly_charges_list = [
    29.99,
    54.50,
    72.25,
    89.99,
    45.00
]

annual_charges_loop = []

for charge in monthly_charges_list:
    annual_charges_loop.append(charge * 12)

print(annual_charges_loop)

[359.88, 654.0, 867.0, 1079.8799999999999, 540.0]


In [12]:
monthly_charges_array = np.array(monthly_charges_list)

annual_charges_numpy = monthly_charges_array * 12

print(annual_charges_numpy)

[ 359.88  654.    867.   1079.88  540.  ]


In [13]:
large_array = np.arange(1, 1_000_001)
large_list = list(range(1, 1_000_001))

In [14]:
%%time

squared_loop = []

for number in large_list:
    squared_loop.append(number ** 2)

CPU times: user 111 ms, sys: 15 ms, total: 126 ms
Wall time: 125 ms


In [15]:
%%time

squared_numpy = large_array ** 2

CPU times: user 0 ns, sys: 5.25 ms, total: 5.25 ms
Wall time: 5.56 ms


In [16]:
monthly_charges = np.array([
    30.00,
    45.00,
    60.00,
    75.00
])

service_fee = 5.00

charges_with_fee = monthly_charges + service_fee

print(charges_with_fee)

[35. 50. 65. 80.]


In [17]:
customer_data = np.array([
    [30, 10],
    [45, 20],
    [60, 30]
])

adjustments = np.array([5, 2])

adjusted_data = customer_data + adjustments

print(adjusted_data)

[[35 12]
 [50 22]
 [65 32]]


In [18]:
monthly_charges = np.array([
    29.99,
    54.50,
    72.25,
    89.99,
    45.00
])

high_charge_mask = monthly_charges > 60

print(high_charge_mask)

[False False  True  True False]


In [20]:
print(monthly_charges[monthly_charges > 60])

[72.25 89.99]


In [21]:
medium_charges = monthly_charges[
    (monthly_charges >= 40) &
    (monthly_charges <= 75)
]

print(medium_charges)

[54.5  72.25 45.  ]


In [22]:
print("Minimum:", np.min(monthly_charges))
print("Maximum:", np.max(monthly_charges))
print("Average:", np.mean(monthly_charges))
print("Median:", np.median(monthly_charges))
print("Total:", np.sum(monthly_charges))
print("Standard deviation:", np.std(monthly_charges))

Minimum: 29.99
Maximum: 89.99
Average: 58.346000000000004
Median: 54.5
Total: 291.73
Standard deviation: 20.936256207832383


In [23]:
average_charge = np.mean(monthly_charges)

print(f"Average monthly charge: ${average_charge:.2f}")

Average monthly charge: $58.35


In [24]:
customer_metrics = np.array([
    [12, 29.99],
    [24, 54.50],
    [36, 72.25],
    [6, 89.99]
])

print(customer_metrics)

[[12.   29.99]
 [24.   54.5 ]
 [36.   72.25]
 [ 6.   89.99]]


In [25]:
tenure = customer_metrics[:, 0]

print(tenure)

[12. 24. 36.  6.]


In [26]:
charges = customer_metrics[:, 1]

print(charges)

[29.99 54.5  72.25 89.99]


In [27]:
column_averages = np.mean(
    customer_metrics,
    axis=0
)

print(column_averages)

[19.5    61.6825]
